
name: delivery
description: "A delivery management application."

version: 1.0.0+1

environment:
  sdk: ^3.9.0-155.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.5
  intl: ^0.18.1  # or latest version
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  http: ^1.4.0
  permission_handler: ^11.0.0
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.20
  image_picker: ^1.0.4
  path: any
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#1E88E5"  # Background color matching your theme
  image: assets/images/logo.png  # Your logo image
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/delivery-address.png
    - assets/images/delivery_truck.png